[tool.poetry]
name = "pulsee"
version = "0.1.4"
description = "Program for the Simulation of Nuclear Spin Ensemble Evolution"
authors = ["Jiwoo Seo <lemon6927@gmail.com>", "Alan Bidart <alanbidart@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cython = "<3"
ipykernel = "^6.29.0"
ipyparallel = "^8.6.1"
matplotlib = "^3.8.2"
numpy = "^1.26.3"
pandas = "^2.2.0"
qutip = "^4.7.5"
scipy = "^1.12.0"
tqdm = "^4.66.1"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
